package de.hsbremerhaven.pongservice.domain;

public enum Event {
    GAME_TICK, ROOM_ENTRY_ERROR_MESSAGE, PADDLE_MOVEMENT, NEW_CUSTOM_PADDLE, RESET_CUSTOM_PADDLE, FORCED_TO_SPECTATE, START_MATCH, INGAME_MESSAGE
}
